---
api_domain: justlog.gempir.com
email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65373739353434323038366266343639376262633166356330336339396664326264343334633864
          6164633261343062623666613536343265663038343330360a313637663739343464396133366565
          35666538386231343533333231646131383734663834663039636235313237636366343535376366
          3438353430666537630a323338663565366439353163646435633738653563393330613064363163
          66356363623063373532626262343361663933623132653162633034396131623038
admin: gempir
channels: "gempir,pajlada"